"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var p = new point_1.Point(1, 2);
var p1 = new point_1.Point(4);
console.log(p1.X);
console.log('test autosave');
p.draw();
p1.draw();
p.distance(p1);
