"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var like_1 = require("./like");
var like = new like_1.Like(false, 0);
like.onClick();
like.onClick();
like.onClick();
like.onClick();
like.onClick();
like.onClick();
like.onClick();
like.onClick();
console.log(like.count);
